# Generated by Django 5.0.7 on 2024-07-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsuplementos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=255, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto',
            field=models.CharField(max_length=255, verbose_name='Produto'),
        ),
    ]
