# Generated by Django 5.0.7 on 2024-07-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsuplementos', '0002_alter_produto_marca_alter_produto_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=1000, verbose_name='Descrição'),
        ),
    ]
